# ===============================
# DATABASE CONFIGURATION (WAMP)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/crm_online?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080
# ==============================
# CLOUDINARY CONFIGURATION
# ==============================
cloudinary.cloud-name=dic1jzc0w
cloudinary.api-key=847263998156561
cloudinary.api-secret=oNGq7En6Ds9GT207XroWXumkMh0