# ===============================
# DATABASE CONFIGURATION (WAMP)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/crm_system?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / HIBERNATE CONFIGURATION
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=8080
# ==============================
# CLOUDINARY CONFIGURATION
# ==============================
cloudinary.cloud-name=dic1jzc0w
cloudinary.api-key=847263998156561
cloudinary.api-secret=oNGq7En6Ds9GT207XroWXumkMh0
jwt.secret=VTI_CRM_Super_Secret_Key_For_JWT_Token_Generation_2026_Ho_Chi_Minh
jwt.expirationMs=86400000